modules: build: fix
Signed-off-by: AuxXxilium <info@auxxxilium.tech>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -127,191 +127,191 @@ jobs:
             [ -n "${CCVER}" ] && echo "CCVER=${CCVER}" >> $GITHUB_ENV
           fi
 
-        - name: Get Src
-          run: |
-            ROOT_PATH=${{ github.workspace }}
-  
-            mkdir -p ${ROOT_PATH}/source/output
-            repo=${{ env.repo }}
-            KVER=${{ env.KVER }}
-  
-            sudo cp -a ${ROOT_PATH}/src/${KVER:0:1}.x ${ROOT_PATH}/source/input
-  
-            sudo cp -a ${ROOT_PATH}/source ${ROOT_PATH}/build_env/ds.${{ matrix.platform }}-${{ matrix.version }}/
-  
-        - name: Make
-          run: |
-            ROOT_PATH=${{ github.workspace }}
-  
-            sudo chroot build_env/ds.${{ matrix.platform }}-${{ matrix.version }} << "EOF"
-            sed -i 's/^CFLAGS=/#CFLAGS=/g; s/^CXXFLAGS=/#CXXFLAGS=/g' /env${BUILD_ARCH}.mak
-            while read line; do if [ ${line:0:1} != "#" ]; then export ${line%%=*}="${line#*=}"; fi; done < /env${BUILD_ARCH}.mak
-            cd /source/input
-            [ -z "`grep 'env.mak' Makefile`" ] && sed -i '1 i include /env.mak' Makefile
-  
-            if [ -f "defines.${{ matrix.platform }}" ]; then
-              PARMS+=" `cat "defines.${{ matrix.platform }}" | xargs`"
-            else
-              echo "[E] ${{ matrix.platform }}-${{ matrix.version }}"
-            fi
-            make -j`nproc` -C "${KSRC}" M="${PWD}" ${PARMS} modules
-            while read F; do
-              strip -g "${F}"
-              echo "Copying `basename ${F}`"
-              cp "${F}" "/source/output"
-            done < <(find ${PWD} -name \*.ko)
-            EOF
-  
-            sudo cp -a ${ROOT_PATH}/build_env/ds.${{ matrix.platform }}-${{ matrix.version }}/source/output ${ROOT_PATH}/source/
-            sudo chmod a+rw -R ${ROOT_PATH}/source/output
+      - name: Get Src
+        run: |
+          ROOT_PATH=${{ github.workspace }}
 
-        - name: Tar to Artifacts
-          run: |
-            OFFICIAL_PATH="${{ github.workspace }}/official/hda1/${{ matrix.platform }}-${{ env.KVER }}"
-            PARTY3RD_PATH="${{ github.workspace }}/thirdparty/${{ matrix.platform }}-${{ env.KVER }}"
+          mkdir -p ${ROOT_PATH}/source/output
+          repo=${{ env.repo }}
+          KVER=${{ env.KVER }}
 
-            echo "copy 3rd modules"
-            [ -d "${PARTY3RD_PATH}" ] && cp -rf "${PARTY3RD_PATH}/." "${{ github.workspace }}/source/output"
-            
-            echo "copy official modules"
-            OM=(cpufreq_performance i915 processor ehci-hcd ehci-pci uhci-hcd xhci-hcd xhci-pci)
-            for M in ${OM[@]}; do
-              function _copydepends() {
-                [ -f "${OFFICIAL_PATH}/${1}" ] && [ ! -f "${OFFICIAL_PATH/hda1/rd}/${1}" ] && cp -f "${OFFICIAL_PATH}/${1}" "${{ github.workspace }}/source/output"
-                depends=($(modinfo "${OFFICIAL_PATH}/${1}" | grep depends: | awk -F: '{print $2}' | awk '$1=$1' | sed 's/,/ /g'))
-                if [ ${#depends[*]} -gt 0 ]; then
-                  for k in ${depends[@]}; do
-                    _copydepends "${k}.ko"
-                  done
-                fi
-              }
-              _copydepends "${M}.ko"
-            done
-  
-            echo "check depends"
-            for M in `ls ${{ github.workspace }}/source/output`; do
-              depends=(`modinfo "${{ github.workspace }}/source/output/${M}" | grep depends: | awk -F: '{print $2}' | awk '$1=$1' | sed 's/,/ /g'`)
+          sudo cp -a ${ROOT_PATH}/src/${KVER:0:1}.x ${ROOT_PATH}/source/input
+
+          sudo cp -a ${ROOT_PATH}/source ${ROOT_PATH}/build_env/ds.${{ matrix.platform }}-${{ matrix.version }}/
+
+      - name: Make
+        run: |
+          ROOT_PATH=${{ github.workspace }}
+
+          sudo chroot build_env/ds.${{ matrix.platform }}-${{ matrix.version }} << "EOF"
+          sed -i 's/^CFLAGS=/#CFLAGS=/g; s/^CXXFLAGS=/#CXXFLAGS=/g' /env${BUILD_ARCH}.mak
+          while read line; do if [ ${line:0:1} != "#" ]; then export ${line%%=*}="${line#*=}"; fi; done < /env${BUILD_ARCH}.mak
+          cd /source/input
+          [ -z "`grep 'env.mak' Makefile`" ] && sed -i '1 i include /env.mak' Makefile
+
+          if [ -f "defines.${{ matrix.platform }}" ]; then
+            PARMS+=" `cat "defines.${{ matrix.platform }}" | xargs`"
+          else
+            echo "[E] ${{ matrix.platform }}-${{ matrix.version }}"
+          fi
+          make -j`nproc` -C "${KSRC}" M="${PWD}" ${PARMS} modules
+          while read F; do
+            strip -g "${F}"
+            echo "Copying `basename ${F}`"
+            cp "${F}" "/source/output"
+          done < <(find ${PWD} -name \*.ko)
+          EOF
+
+          sudo cp -a ${ROOT_PATH}/build_env/ds.${{ matrix.platform }}-${{ matrix.version }}/source/output ${ROOT_PATH}/source/
+          sudo chmod a+rw -R ${ROOT_PATH}/source/output
+
+      - name: Tar to Artifacts
+        run: |
+          OFFICIAL_PATH="${{ github.workspace }}/official/hda1/${{ matrix.platform }}-${{ env.KVER }}"
+          PARTY3RD_PATH="${{ github.workspace }}/thirdparty/${{ matrix.platform }}-${{ env.KVER }}"
+
+          echo "copy 3rd modules"
+          [ -d "${PARTY3RD_PATH}" ] && cp -rf "${PARTY3RD_PATH}/." "${{ github.workspace }}/source/output"
+          
+          echo "copy official modules"
+          OM=(cpufreq_performance i915 processor ehci-hcd ehci-pci uhci-hcd xhci-hcd xhci-pci)
+          for M in ${OM[@]}; do
+            function _copydepends() {
+              [ -f "${OFFICIAL_PATH}/${1}" ] && [ ! -f "${OFFICIAL_PATH/hda1/rd}/${1}" ] && cp -f "${OFFICIAL_PATH}/${1}" "${{ github.workspace }}/source/output"
+              depends=($(modinfo "${OFFICIAL_PATH}/${1}" | grep depends: | awk -F: '{print $2}' | awk '$1=$1' | sed 's/,/ /g'))
               if [ ${#depends[*]} -gt 0 ]; then
                 for k in ${depends[@]}; do
-                  if [ ! -f "${{ github.workspace }}/source/output/${k}.ko" ]; then
-                    [ -f "${OFFICIAL_PATH}/${k}.ko" ] && FLAG=O || FLAG=X
-                    echo "[W][${FLAG}] '${{ matrix.platform }}-${{ env.KVER }}' - '${M}' depends '${k}' does not exist."
-                  fi
+                  _copydepends "${k}.ko"
                 done
               fi
-            done
-            if [ "${{ matrix.platform }}" = "epyc7002" ]; then
-              tar caf ${{ github.workspace }}/source/${{ matrix.platform }}-${{ matrix.version }}-${{ env.KVER }}.tgz -C ${{ github.workspace }}/source/output .
-            else
-              tar caf ${{ github.workspace }}/source/${{ matrix.platform }}-${{ env.KVER }}.tgz -C ${{ github.workspace }}/source/output .
-            fi
-  
-        - name: Upload to Artifacts
-          uses: actions/upload-artifact@v3
-          with:
-            name: modules
-            path: |
-              ${{ github.workspace }}/source/*.tgz
-              
-        - name: clean
-          run: |
-            sudo rm -rf ${{ github.workspace }}/build_env/ds.${{ matrix.platform }}-${{ matrix.version }}/source/*
-  
-  
-    firmware:
-      runs-on: ubuntu-latest
-      needs: build
-      steps:
-        - name: Checkout
-          uses: actions/checkout@main
-  
-        - name: download to artifacts
-          uses: actions/download-artifact@v3
-          with:
-            name: modules
-            path: ./modules
-  
-        - name: firmware
-          run: |
-            mkdir -p firmware
-  
-            echo "copy 3rd modules"
-            PARTY3RD_PATH="${{ github.workspace }}/thirdparty/firmware"
-            cp -rf ${PARTY3RD_PATH}/* firmware/
-  
-            echo "extract all modules"
-            for F in ./modules/*.tgz; do mkdir "${F%.tgz}" && tar -xzf "${F}" -C "${F%.tgz}"; done
-            
-            echo "get firmware"
-            SOURCE=/tmp/linux-firmware
-            git clone https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git ${SOURCE}
-            while read L; do
-              if [ -e "${SOURCE}/${L}" ]; then
-                mkdir -p "`dirname firmware/${L}`"
-                cp "${SOURCE}/${L}" "firmware/${L}"
-              else
-                [ -e "firmware/${L}" ] && echo "Used thirdparty ${L}" || echo "Missing ${L}"
-              fi
-            done < <(find ./modules -name \*.ko -exec sh -c '/sbin/modinfo {} | grep ^firmware' \; | awk '{print $2}')
-  
-            tar caf firmware.tgz -C firmware .
-  
-  
-        - name: Upload to Artifacts
-          uses: actions/upload-artifact@v3
-          with:
-            name: modules
-            path: |
-              firmware.tgz
-  
-  
-    release:
-      runs-on: ubuntu-latest
-      needs: firmware
-      steps:
-        - name: Checkout
-          uses: actions/checkout@main
-  
-        - name: Calculate version
-          run: |
-            # Calculate version
-            VERSION=""
-            if [ ${{ github.event_name }} == 'release' -a ${{ github.ref_type }} == 'tag' ]; then
-              VERSION="${{ github.ref_name }}"
-            elif [ -n "${{ inputs.version }}" ]; then
-              if [ "`echo ${{ inputs.version }} | cut -d '.' -f 1,2`" = "`date +'%y.%-m'`" ]; then
-                VERSION="${{ inputs.version }}"
-              else
-                LATEST_TAG="`curl -skL "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r ".tag_name" 2>/dev/null`"
-                if [ -n "${LATEST_TAG}" -a "`echo ${LATEST_TAG} | cut -d '.' -f 1,2`" = "`date +'%y.%-m'`" ]; then  # format %y.%-m.$i
-                  VERSION="`echo ${LATEST_TAG} | awk -F '.' '{$3=$3+1}1' OFS='.'`"
-                else
-                  VERSION="`date +'%y.%-m'`.0"
+            }
+            _copydepends "${M}.ko"
+          done
+
+          echo "check depends"
+          for M in `ls ${{ github.workspace }}/source/output`; do
+            depends=(`modinfo "${{ github.workspace }}/source/output/${M}" | grep depends: | awk -F: '{print $2}' | awk '$1=$1' | sed 's/,/ /g'`)
+            if [ ${#depends[*]} -gt 0 ]; then
+              for k in ${depends[@]}; do
+                if [ ! -f "${{ github.workspace }}/source/output/${k}.ko" ]; then
+                  [ -f "${OFFICIAL_PATH}/${k}.ko" ] && FLAG=O || FLAG=X
+                  echo "[W][${FLAG}] '${{ matrix.platform }}-${{ env.KVER }}' - '${M}' depends '${k}' does not exist."
                 fi
-              fi
-            else
-              VERSION=""
+              done
             fi
-  
-            echo "VERSION: ${VERSION}"
-            echo "VERSION=${VERSION}" >> $GITHUB_ENV
-  
-        - name: download to artifacts
-          if: env.VERSION != ''
-          uses: actions/download-artifact@v3
-          with:
-            name: modules
-            path: ./modules
-  
-        - name: Zip modules
-          if: env.VERSION != ''
-          run: |
-            echo "${{ env.VERSION }}" > "modules/VERSION"
-            zip -9 modules.zip -j modules/*
-  
-        - name: Release
-          uses: softprops/action-gh-release@v1
-          if: env.VERSION != ''
-          with:
-            tag_name: ${{ env.VERSION }}
-            files: modules.zip
+          done
+          if [ "${{ matrix.platform }}" = "epyc7002" ]; then
+            tar caf ${{ github.workspace }}/source/${{ matrix.platform }}-${{ matrix.version }}-${{ env.KVER }}.tgz -C ${{ github.workspace }}/source/output .
+          else
+            tar caf ${{ github.workspace }}/source/${{ matrix.platform }}-${{ env.KVER }}.tgz -C ${{ github.workspace }}/source/output .
+          fi
+
+      - name: Upload to Artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: modules
+          path: |
+            ${{ github.workspace }}/source/*.tgz
+            
+      - name: clean
+        run: |
+          sudo rm -rf ${{ github.workspace }}/build_env/ds.${{ matrix.platform }}-${{ matrix.version }}/source/*
+
+
+  firmware:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout
+        uses: actions/checkout@main
+
+      - name: download to artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: modules
+          path: ./modules
+
+      - name: firmware
+        run: |
+          mkdir -p firmware
+
+          echo "copy 3rd modules"
+          PARTY3RD_PATH="${{ github.workspace }}/thirdparty/firmware"
+          cp -rf ${PARTY3RD_PATH}/* firmware/
+
+          echo "extract all modules"
+          for F in ./modules/*.tgz; do mkdir "${F%.tgz}" && tar -xzf "${F}" -C "${F%.tgz}"; done
+          
+          echo "get firmware"
+          SOURCE=/tmp/linux-firmware
+          git clone https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git ${SOURCE}
+          while read L; do
+            if [ -e "${SOURCE}/${L}" ]; then
+              mkdir -p "`dirname firmware/${L}`"
+              cp "${SOURCE}/${L}" "firmware/${L}"
+            else
+              [ -e "firmware/${L}" ] && echo "Used thirdparty ${L}" || echo "Missing ${L}"
+            fi
+          done < <(find ./modules -name \*.ko -exec sh -c '/sbin/modinfo {} | grep ^firmware' \; | awk '{print $2}')
+
+          tar caf firmware.tgz -C firmware .
+
+
+      - name: Upload to Artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: modules
+          path: |
+            firmware.tgz
+
+
+  release:
+    runs-on: ubuntu-latest
+    needs: firmware
+    steps:
+      - name: Checkout
+        uses: actions/checkout@main
+
+      - name: Calculate version
+        run: |
+          # Calculate version
+          VERSION=""
+          if [ ${{ github.event_name }} == 'release' -a ${{ github.ref_type }} == 'tag' ]; then
+            VERSION="${{ github.ref_name }}"
+          elif [ -n "${{ inputs.version }}" ]; then
+            if [ "`echo ${{ inputs.version }} | cut -d '.' -f 1,2`" = "`date +'%y.%-m'`" ]; then
+              VERSION="${{ inputs.version }}"
+            else
+              LATEST_TAG="`curl -skL "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r ".tag_name" 2>/dev/null`"
+              if [ -n "${LATEST_TAG}" -a "`echo ${LATEST_TAG} | cut -d '.' -f 1,2`" = "`date +'%y.%-m'`" ]; then  # format %y.%-m.$i
+                VERSION="`echo ${LATEST_TAG} | awk -F '.' '{$3=$3+1}1' OFS='.'`"
+              else
+                VERSION="`date +'%y.%-m'`.0"
+              fi
+            fi
+          else
+            VERSION=""
+          fi
+
+          echo "VERSION: ${VERSION}"
+          echo "VERSION=${VERSION}" >> $GITHUB_ENV
+
+      - name: download to artifacts
+        if: env.VERSION != ''
+        uses: actions/download-artifact@v3
+        with:
+          name: modules
+          path: ./modules
+
+      - name: Zip modules
+        if: env.VERSION != ''
+        run: |
+          echo "${{ env.VERSION }}" > "modules/VERSION"
+          zip -9 modules.zip -j modules/*
+
+      - name: Release
+        uses: softprops/action-gh-release@v1
+        if: env.VERSION != ''
+        with:
+          tag_name: ${{ env.VERSION }}
+          files: modules.zip
